// Generated by gencpp from file daimler_tugger/daimler_service_callRequest.msg
// DO NOT EDIT!


#ifndef DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLREQUEST_H
#define DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daimler_tugger
{
template <class ContainerAllocator>
struct daimler_service_callRequest_
{
  typedef daimler_service_callRequest_<ContainerAllocator> Type;

  daimler_service_callRequest_()
    : Set_Undock_State(false)
    , Set_Dock_State(false)  {
    }
  daimler_service_callRequest_(const ContainerAllocator& _alloc)
    : Set_Undock_State(false)
    , Set_Dock_State(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Set_Undock_State_type;
  _Set_Undock_State_type Set_Undock_State;

   typedef uint8_t _Set_Dock_State_type;
  _Set_Dock_State_type Set_Dock_State;





  typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> const> ConstPtr;

}; // struct daimler_service_callRequest_

typedef ::daimler_tugger::daimler_service_callRequest_<std::allocator<void> > daimler_service_callRequest;

typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callRequest > daimler_service_callRequestPtr;
typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callRequest const> daimler_service_callRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator1> & lhs, const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Set_Undock_State == rhs.Set_Undock_State &&
    lhs.Set_Dock_State == rhs.Set_Dock_State;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator1> & lhs, const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace daimler_tugger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56af2ae496e170116ca62c16fe9d2a89";
  }

  static const char* value(const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56af2ae496e17011ULL;
  static const uint64_t static_value2 = 0x6ca62c16fe9d2a89ULL;
};

template<class ContainerAllocator>
struct DataType< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daimler_tugger/daimler_service_callRequest";
  }

  static const char* value(const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Set_Undock_State\n"
"bool Set_Dock_State\n"
;
  }

  static const char* value(const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Set_Undock_State);
      stream.next(m.Set_Dock_State);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct daimler_service_callRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daimler_tugger::daimler_service_callRequest_<ContainerAllocator>& v)
  {
    s << indent << "Set_Undock_State: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Set_Undock_State);
    s << indent << "Set_Dock_State: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Set_Dock_State);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLREQUEST_H
