// Generated by gencpp from file daimler_tugger/daimler_service_call.msg
// DO NOT EDIT!


#ifndef DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALL_H
#define DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALL_H

#include <ros/service_traits.h>


#include <daimler_tugger/daimler_service_callRequest.h>
#include <daimler_tugger/daimler_service_callResponse.h>


namespace daimler_tugger
{

struct daimler_service_call
{

typedef daimler_service_callRequest Request;
typedef daimler_service_callResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct daimler_service_call
} // namespace daimler_tugger


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::daimler_tugger::daimler_service_call > {
  static const char* value()
  {
    return "dd04567e9742c14ebff061ebed5af4a1";
  }

  static const char* value(const ::daimler_tugger::daimler_service_call&) { return value(); }
};

template<>
struct DataType< ::daimler_tugger::daimler_service_call > {
  static const char* value()
  {
    return "daimler_tugger/daimler_service_call";
  }

  static const char* value(const ::daimler_tugger::daimler_service_call&) { return value(); }
};


// service_traits::MD5Sum< ::daimler_tugger::daimler_service_callRequest> should match
// service_traits::MD5Sum< ::daimler_tugger::daimler_service_call >
template<>
struct MD5Sum< ::daimler_tugger::daimler_service_callRequest>
{
  static const char* value()
  {
    return MD5Sum< ::daimler_tugger::daimler_service_call >::value();
  }
  static const char* value(const ::daimler_tugger::daimler_service_callRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::daimler_tugger::daimler_service_callRequest> should match
// service_traits::DataType< ::daimler_tugger::daimler_service_call >
template<>
struct DataType< ::daimler_tugger::daimler_service_callRequest>
{
  static const char* value()
  {
    return DataType< ::daimler_tugger::daimler_service_call >::value();
  }
  static const char* value(const ::daimler_tugger::daimler_service_callRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::daimler_tugger::daimler_service_callResponse> should match
// service_traits::MD5Sum< ::daimler_tugger::daimler_service_call >
template<>
struct MD5Sum< ::daimler_tugger::daimler_service_callResponse>
{
  static const char* value()
  {
    return MD5Sum< ::daimler_tugger::daimler_service_call >::value();
  }
  static const char* value(const ::daimler_tugger::daimler_service_callResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::daimler_tugger::daimler_service_callResponse> should match
// service_traits::DataType< ::daimler_tugger::daimler_service_call >
template<>
struct DataType< ::daimler_tugger::daimler_service_callResponse>
{
  static const char* value()
  {
    return DataType< ::daimler_tugger::daimler_service_call >::value();
  }
  static const char* value(const ::daimler_tugger::daimler_service_callResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALL_H
