// Generated by gencpp from file daimler_tugger/DaimlerServiceCallRequest.msg
// DO NOT EDIT!


#ifndef DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALLREQUEST_H
#define DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daimler_tugger
{
template <class ContainerAllocator>
struct DaimlerServiceCallRequest_
{
  typedef DaimlerServiceCallRequest_<ContainerAllocator> Type;

  DaimlerServiceCallRequest_()
    : Set_Dock_State(false)  {
    }
  DaimlerServiceCallRequest_(const ContainerAllocator& _alloc)
    : Set_Dock_State(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Set_Dock_State_type;
  _Set_Dock_State_type Set_Dock_State;





  typedef boost::shared_ptr< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DaimlerServiceCallRequest_

typedef ::daimler_tugger::DaimlerServiceCallRequest_<std::allocator<void> > DaimlerServiceCallRequest;

typedef boost::shared_ptr< ::daimler_tugger::DaimlerServiceCallRequest > DaimlerServiceCallRequestPtr;
typedef boost::shared_ptr< ::daimler_tugger::DaimlerServiceCallRequest const> DaimlerServiceCallRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator1> & lhs, const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Set_Dock_State == rhs.Set_Dock_State;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator1> & lhs, const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace daimler_tugger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cd660de3b311f808084e2d9abd2644a";
  }

  static const char* value(const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cd660de3b311f80ULL;
  static const uint64_t static_value2 = 0x8084e2d9abd2644aULL;
};

template<class ContainerAllocator>
struct DataType< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daimler_tugger/DaimlerServiceCallRequest";
  }

  static const char* value(const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Set_Dock_State\n"
;
  }

  static const char* value(const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Set_Dock_State);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DaimlerServiceCallRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daimler_tugger::DaimlerServiceCallRequest_<ContainerAllocator>& v)
  {
    s << indent << "Set_Dock_State: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Set_Dock_State);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALLREQUEST_H
