// Generated by gencpp from file daimler_tugger/DaimlerServiceCall.msg
// DO NOT EDIT!


#ifndef DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALL_H
#define DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALL_H

#include <ros/service_traits.h>


#include <daimler_tugger/DaimlerServiceCallRequest.h>
#include <daimler_tugger/DaimlerServiceCallResponse.h>


namespace daimler_tugger
{

struct DaimlerServiceCall
{

typedef DaimlerServiceCallRequest Request;
typedef DaimlerServiceCallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DaimlerServiceCall
} // namespace daimler_tugger


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::daimler_tugger::DaimlerServiceCall > {
  static const char* value()
  {
    return "9ac08f7e71c0b3bbe9b763939b61b7bb";
  }

  static const char* value(const ::daimler_tugger::DaimlerServiceCall&) { return value(); }
};

template<>
struct DataType< ::daimler_tugger::DaimlerServiceCall > {
  static const char* value()
  {
    return "daimler_tugger/DaimlerServiceCall";
  }

  static const char* value(const ::daimler_tugger::DaimlerServiceCall&) { return value(); }
};


// service_traits::MD5Sum< ::daimler_tugger::DaimlerServiceCallRequest> should match
// service_traits::MD5Sum< ::daimler_tugger::DaimlerServiceCall >
template<>
struct MD5Sum< ::daimler_tugger::DaimlerServiceCallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::daimler_tugger::DaimlerServiceCall >::value();
  }
  static const char* value(const ::daimler_tugger::DaimlerServiceCallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::daimler_tugger::DaimlerServiceCallRequest> should match
// service_traits::DataType< ::daimler_tugger::DaimlerServiceCall >
template<>
struct DataType< ::daimler_tugger::DaimlerServiceCallRequest>
{
  static const char* value()
  {
    return DataType< ::daimler_tugger::DaimlerServiceCall >::value();
  }
  static const char* value(const ::daimler_tugger::DaimlerServiceCallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::daimler_tugger::DaimlerServiceCallResponse> should match
// service_traits::MD5Sum< ::daimler_tugger::DaimlerServiceCall >
template<>
struct MD5Sum< ::daimler_tugger::DaimlerServiceCallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::daimler_tugger::DaimlerServiceCall >::value();
  }
  static const char* value(const ::daimler_tugger::DaimlerServiceCallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::daimler_tugger::DaimlerServiceCallResponse> should match
// service_traits::DataType< ::daimler_tugger::DaimlerServiceCall >
template<>
struct DataType< ::daimler_tugger::DaimlerServiceCallResponse>
{
  static const char* value()
  {
    return DataType< ::daimler_tugger::DaimlerServiceCall >::value();
  }
  static const char* value(const ::daimler_tugger::DaimlerServiceCallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DAIMLER_TUGGER_MESSAGE_DAIMLERSERVICECALL_H
