// Generated by gencpp from file daimler_tugger/daimler_service_callResponse.msg
// DO NOT EDIT!


#ifndef DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLRESPONSE_H
#define DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace daimler_tugger
{
template <class ContainerAllocator>
struct daimler_service_callResponse_
{
  typedef daimler_service_callResponse_<ContainerAllocator> Type;

  daimler_service_callResponse_()
    : Result(false)  {
    }
  daimler_service_callResponse_(const ContainerAllocator& _alloc)
    : Result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Result_type;
  _Result_type Result;





  typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> const> ConstPtr;

}; // struct daimler_service_callResponse_

typedef ::daimler_tugger::daimler_service_callResponse_<std::allocator<void> > daimler_service_callResponse;

typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callResponse > daimler_service_callResponsePtr;
typedef boost::shared_ptr< ::daimler_tugger::daimler_service_callResponse const> daimler_service_callResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator1> & lhs, const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Result == rhs.Result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator1> & lhs, const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace daimler_tugger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85ed39ee8c4e8f1c21743e6fe4dd523e";
  }

  static const char* value(const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85ed39ee8c4e8f1cULL;
  static const uint64_t static_value2 = 0x21743e6fe4dd523eULL;
};

template<class ContainerAllocator>
struct DataType< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "daimler_tugger/daimler_service_callResponse";
  }

  static const char* value(const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Result\n"
;
  }

  static const char* value(const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct daimler_service_callResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::daimler_tugger::daimler_service_callResponse_<ContainerAllocator>& v)
  {
    s << indent << "Result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAIMLER_TUGGER_MESSAGE_DAIMLER_SERVICE_CALLRESPONSE_H
