(cl:defpackage daimler_tugger-srv
  (:use )
  (:export
   "DAIMLERSERVICECALL"
   "<DAIMLERSERVICECALL-REQUEST>"
   "DAIMLERSERVICECALL-REQUEST"
   "<DAIMLERSERVICECALL-RESPONSE>"
   "DAIMLERSERVICECALL-RESPONSE"
  ))

